4 spaces for indentation

diff --git a/trivial-validate b/trivial-validate
--- a/trivial-validate
+++ b/trivial-validate
@@ -109,28 +109,28 @@ echo
 echo "-- Rules with syntactically invalid regular expressions:"
 for f in *.xml
 do
-   grep from= $f | cut -d\" -f2 | egrep -f - 2>/dev/null
-   if [ $? -eq 2 ]
-   then
-       echo $f
-       fail=true
-       none=false
-   fi
+    grep from= "$f" | cut -d\" -f2 | egrep -f - 2>/dev/null
+    if [ $? -eq 2 ]
+    then
+        echo "$f"
+        fail=true
+        none=false
+    fi
 done
 $none && echo "(None.)"
 
 echo
 if [ $(which xmllint) ]
 then
-  echo "-- Rules with syntatically invalid XML:"
-  none=true
+    echo "-- Rules with syntatically invalid XML:"
+    none=true
     for rule in *.xml
     do
-      xmllint "$rule" >/dev/null 2>&1 || { echo $rule; none=false; fail=true; }
+        xmllint "$rule" >/dev/null 2>&1 || { echo $rule; none=false; fail=true; }
     done
-  $none && echo "(None.)"
+    $none && echo "(None.)"
 else
-  echo "-- Could not check XML validity because xmllint not found."
+    echo "-- Could not check XML validity because xmllint not found."
 fi
 
 echo
@@ -138,13 +138,13 @@ echo "-- Rules containing non-ASCII characters (possible homoglyph attacks):"
 none=true
 for i in *.xml
 do
-  if egrep '(from|to)=' "$i" | tr -d '[:print:][:space:]' | grep . >/dev/null
-  then
-    echo "$i contains non-ASCII character(s)."
-    none=false
-    #fail=true
-    echo "(not exiting)"
-  fi
+    if egrep '(from|to)=' "$i" | tr -d '[:print:][:space:]' | grep . >/dev/null
+    then
+        echo "$i contains non-ASCII character(s)."
+        none=false
+        #fail=true
+        echo "(not exiting)"
+    fi
 done
 $none && echo "(None.)"
 
@@ -153,12 +153,12 @@ echo "--- Rules that lack at least one valid <target> tag:"
 none=true
 for i in *.xml
 do
-  if ! egrep '<target .*host=".*/>' "$i" >/dev/null
-  then
-    echo $i
-    none=false
-    fail=true
-  fi
+    if ! egrep '<target .*host=".*/>' "$i" >/dev/null
+    then
+        echo $i
+        none=false
+        fail=true
+    fi
 done
 $none && echo "(None.)"
 
@@ -166,18 +166,18 @@ echo
 echo "--- Duplicated ruleset names:"
 if cat *.xml | grep 'ruleset name' | cut -d\" -f2 | sort | uniq -d | grep .
 then
-   fail=true
+    fail=true
 else
-   echo "(None.)"
+    echo "(None.)"
 fi
 
 echo
 echo "--- Duplicated target hosts:"
 if cat *.xml | grep '<target host=' | cut -d\" -f2 | sort | uniq -d | grep .
 then
-   echo "(not exiting)"
+    echo "(not exiting)"
 else
-   echo "(None.)"
+    echo "(None.)"
 fi
 
 if $fail
