pass from expressions to egrep to validate them syntactically

diff --git a/trivial-validate b/trivial-validate
--- a/trivial-validate
+++ b/trivial-validate
@@ -95,6 +95,21 @@ else
    echo "(None.)"
 fi
 
+none=true
+echo
+echo "-- Rules with syntactically invalid regular expressions:"
+for f in *.xml
+do
+   grep from= $f | cut -d\" -f2 | egrep -f - 2>/dev/null
+   if [ $? -eq 2 ]
+   then
+       echo $f
+       fail=true
+       none=false
+   fi
+done
+$none && echo "(None.)"
+
 echo
 if [ $(which xmllint) ]
 then
