Simpler error handling

diff --git a/trivial-validate b/trivial-validate
--- a/trivial-validate
+++ b/trivial-validate
@@ -15,12 +15,10 @@ then
    exit 2
 fi
 
-fail=false
-
 echo "-- Rules not anchored to beginning of a line:"
 if grep from= *.xml | cut -d\" -f2 | grep '^[^^]'
 then
-   fail=true
+   fail=1
 else
    echo "(None.)"
 fi
@@ -29,7 +27,7 @@ echo
 echo "-- Rules with unescaped dots outside of brackets and left of a slash:"
 if grep from= *.xml | cut -d\" -f2 | sed 's/\[[^]]*\]//g' | egrep 'http.?.?://[^/]*[^\]\.[^*]'
 then
-   fail=true
+   fail=1
 else
    echo "(None.)"
 fi
@@ -38,7 +36,7 @@ echo
 echo "-- Rules with backslashes in to pattern:"
 if grep 'to="' *xml | sed 's/^.*to="//' | sed 's/\".*$//' | grep '\\'
 then
-   fail=true
+   fail=1
 else
    echo "(None.)"
 fi
@@ -47,7 +45,7 @@ echo
 echo "-- Rules not containing trailing slash in from pattern:"
 if grep from= *.xml | cut -d\" -f2 | grep -v '//.*/'
 then
-   fail=true
+   fail=1
 else
    echo "(None.)"
 fi
@@ -56,7 +54,7 @@ echo
 echo "-- Rules not containing trailing slash in to pattern:"
 if grep 'to="' *xml | sed 's/^.*to="//' | sed 's/\".*$//' | grep -v '//.*/'
 then
-   fail=true
+   fail=1
 else
    echo "(None.)"
 fi
@@ -65,7 +63,7 @@ echo
 echo "-- Rules with missing closing slash in rule XML tag:"
 if grep to= *xml | grep '[^/]>'
 then
-   fail=true
+   fail=1
 else
    echo "(None.)"
 fi
@@ -74,7 +72,7 @@ echo
 echo "-- Rules with multiple wildcards in a single target rule:"
 if grep 'target host="' *xml | grep '\*.*\*'
 then
-   fail=true
+   fail=1
 else
    echo "(None.)"
 fi
@@ -83,7 +81,7 @@ echo
 echo "-- Rules with targets containing URLs/paths instead of hostnames:"
 if grep 'target host="' *xml | egrep '="[^"]*/'
 then
-   fail=true
+   fail=1
 else
    echo "(None.)"
 fi
@@ -92,7 +90,7 @@ echo
 echo "-- Rules redirecting to http in to pattern:"
 if grep 'to="' *xml | sed 's/^.*to="//' | sed 's/\".*$//' | grep '^http:'
 then
-   fail=true
+   fail=1
 else
    echo "(None.)"
 fi
@@ -101,7 +99,7 @@ echo
 echo "-- Rules containing space before to pattern:"
 if grep 'to="' *xml | sed 's/^.*to="//' | grep '^ '
 then
-   fail=true
+   fail=1
 else
    echo "(None.)"
 fi
@@ -129,7 +127,7 @@ then
     none=true
     for rule in *.xml
     do
-        xmllint "$rule" >/dev/null 2>&1 || { echo $rule; none=false; fail=true; }
+        xmllint "$rule" >/dev/null 2>&1 || { echo $rule; none=false; fail=1; }
     done
     $none && echo "(None.)"
 else
@@ -145,7 +143,7 @@ do
     then
         echo "$i contains non-ASCII character(s)."
         none=false
-        #fail=true
+        #fail=1
         echo "(not exiting)"
     fi
 done
@@ -160,7 +158,7 @@ do
     then
         echo $i
         none=false
-        fail=true
+        fail=1
     fi
 done
 $none && echo "(None.)"
@@ -169,7 +167,7 @@ echo
 echo "--- Duplicated ruleset names:"
 if cat *.xml | grep 'ruleset name' | cut -d\" -f2 | sort | uniq -d | grep .
 then
-    fail=true
+    fail=1
 else
     echo "(None.)"
 fi
@@ -183,9 +181,4 @@ else
     echo "(None.)"
 fi
 
-if $fail
-then
-  exit 1
-else
-  exit 0
-fi
+exit ${fail-0}
